[package]
org = "shehan"
name = "test_project"
version = "0.1.0"
distribution = "2201.8.6"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"

[build-options]
  observabilityIncluded = true
